<?php

$ddate = date( 'D, d M Y H:i:s +00000' );
echo <<<RSS
<?xml version="1.0" encoding="UTF-8" ?>
<!-- This is a WordPress eXtended RSS file generated by WordPress as an export of your site. -->
<!-- It contains information about your sites posts, pages, comments, categories, and other content. -->
<!-- You may use this file to transfer that content from one site to another. -->
<!-- This file is not intended to serve as a complete backup of your site. -->

<!-- To import this information into a WordPress site follow these steps: -->
<!-- 1. Log in to that site as an administrator. -->
<!-- 2. Go to Tools: Import in the WordPress admin panel. -->
<!-- 3. Install the "WordPress" importer from the list. -->
<!-- 4. Activate & Run Importer. -->
<!-- 5. Upload this file using the form provided on that page. -->
<!-- 6. You will first be asked to map the authors in this export file to users -->
<!--    on the site. For each author, you may choose to map to an -->
<!--    existing user on the site or to create a new user. -->
<!-- 7. WordPress will then import each of the posts, pages, comments, categories, etc. -->
<!--    contained in this file into your site. -->

<!-- generator="WordPress/4.1" created="2015-02-11 15:15" -->
<meta name="generator" content="wpCasa 1.3.7" />
<rss version="2.0"
	xmlns:excerpt="http://wordpress.org/export/1.2/excerpt/"
	xmlns:content="http://purl.org/rss/1.0/modules/content/"
	xmlns:wfw="http://wellformedweb.org/CommentAPI/"
	xmlns:dc="http://purl.org/dc/elements/1.1/"
	xmlns:wp="http://wordpress.org/export/1.2/"
>

<channel>
	<title>Cherokee Ridge Golf Course Homes near Huntsville, Alabama</title>
	<link>http://CherokeeRidgeHomes.com</link>
	<description>Golf Courses and Country Clubs near Huntsville, Alabama</description>
	<pubDate>"{$ddate}"</pubDate>
	<language>en-US</language>
	<wp:wxr_version>1.2</wp:wxr_version>
	<wp:base_site_url>http://CherokeeRidgeHomes.com</wp:base_site_url>
	<wp:base_blog_url>http://CherokeeRidgeHomes.com</wp:base_blog_url>

	<wp:author><wp:author_id>3</wp:author_id><wp:author_login>Mikko</wp:author_login><wp:author_email>Mikko@RealEstate-Huntsville.com</wp:author_email><wp:author_display_name><![CDATA[Mikko Jetsu]]></wp:author_display_name><wp:author_first_name><![CDATA[Mikko]]></wp:author_first_name><wp:author_last_name><![CDATA[Jetsu]]></wp:author_last_name></wp:author>
	<wp:author><wp:author_id>4</wp:author_id><wp:author_login>tiffany</wp:author_login><wp:author_email>Tiffany@RealEstate-Huntsville.com</wp:author_email><wp:author_display_name><![CDATA[Tiffany Sears Moore]]></wp:author_display_name><wp:author_first_name><![CDATA[Tiffany Sears]]></wp:author_first_name><wp:author_last_name><![CDATA[Moore]]></wp:author_last_name></wp:author>
	<wp:author><wp:author_id>2</wp:author_id><wp:author_login>dengland</wp:author_login><wp:author_email>DavidEngland@hotmail.com</wp:author_email><wp:author_display_name><![CDATA[David England]]></wp:author_display_name><wp:author_first_name><![CDATA[David]]></wp:author_first_name><wp:author_last_name><![CDATA[England]]></wp:author_last_name></wp:author>


	<generator>http://wordpress.org/?v=4.1</generator>
<meta name="generator" content="wpCasa 1.3.7" />

RSS;
?>